### ISSUE TITLE
Allow floating ip to be optional

### ISSUE THREAD

**Issue by seansund** [we-work-in-the-cloud/terraform-ibm-vpc-bastion#2]
For deployments where Direct Link or a VPN server will be used in the environment, we need a "Bastion" instance (perhaps more appropriately a "jump server") but don't need to expose the VSI via a floating IP address. In that case, apart from the floating ip address all of the logic provided for this module still holds.

It would be helpful to provide a flag like `disable_public_ip` which is defaulted to `false`. The output would need to be adjusted to return an empty string instead of a value for the public ip.

**Comment by l2fprod** [comment]
makes sense!

**Comment by l2fprod** [comment]
added in latest https://registry.terraform.io/modules/we-work-in-the-cloud/vpc-bastion/ibm/latest
