### ISSUE TITLE
Output the network id for the instance

### ISSUE THREAD

**Issue by seansund** [we-work-in-the-cloud/terraform-ibm-vpc-bastion#4]
For the ibm_is_security_group_network_interface_attachment resource, we need the network interface id. That value can be looked up from the vsi id that is output as `bastion_id` but it would be nice if the network id(s) were included in the output.

**Comment by l2fprod** [comment]
merged your PR, thank you!
https://registry.terraform.io/modules/we-work-in-the-cloud/vpc-bastion/ibm/latest
